# Site settings
title: Alexis Yobanis
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexis Yobanis
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title:Innovador Empresarial 
email: 250300644@ucaribe.edu.mx
# twitter_username:alexis23
instagram_username:carter_000o
facebook_username: carter emil rojas
linkedin_username:alexis
github_username:sedrikv1
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

